name: docker-compose-actions-workflow
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04.5]
    steps:
      - name: Build the stack
          run: docker-compose up -d


